### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'gfile'

### ISSUE THREAD

**Issue by shravankumar9892** [tobegit3hub/simple_tensorflow_serving#45]
I trained a simple **mnist model** with **tensorflow 2.0** on **Google Colab** and saved it in the **.json** format. Then on running the command 

`!simple_tensorflow_serving --model_base_path="/" --model_platform="tensorflow"`

It is showing the error AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by tobegit3hub** [comment]
What's the version of your `tensorflow`? It should has `tf.gfile` by default.

**Comment by anyaozm** [comment]
I had the same error. It's tensorflow 2.0 the new version.

**Comment by tobegit3hub** [comment]
It may be the API change from `TensorFlow 2.0`.

We may change the usage of this API for this newer version.

**Comment by anyaozm** [comment]
Thank you!

**Comment by Tsakunelson** [comment]
Hi @shravankumar9892 @anyaozm, 

Could you solve the problem? My tensorflow version is 2.0.0-alpha0, but i still encounter the "AttributeError: module 'tensorflow' has no attribute 'gfile'" error after running the line '''  simple_tensorflow_serving --model_base_path="./models/tensorflow_template_application_model'''
![image](https://user-images.githubusercontent.com/17685437/57242319-364ffa00-7001-11e9-9f85-292e3af39d65.png)

Thank you

**Comment by anyaozm** [comment]
I uninstalled Tensorflow and all the files from the repository I pip installed. The installed TensorFlow and did the 2nd option and bazel built instead of doing the pip. It worked. You might wanna try pip3 if you’re using python 3. But the other setup worked for me.

**Comment by moabaom** [comment]
any new update on tf.gfile issue ? if the API has changed what would be the new one in TF-2.0 ?

**Comment by tobegit3hub** [comment]
I will update this project for TensorFlow 2.0 when it's officially released. Any contribution is welcome if you are interested in this.

**Comment by AlbertBJ** [comment]
In tf2.0 , the gfile package has been moved into tf.io. so u can use tf.io.gfile

**Comment by tobegit3hub** [comment]
Thanks all. This have been resolved by https://github.com/tobegit3hub/simple_tensorflow_serving/commit/e9adcaa46d6af448321d70bcac0b4544eba4935f .

And we have done more code change to make STFS to run with TensorFlow 2.x now.

**Comment by tobegit3hub** [comment]
Related to https://github.com/tobegit3hub/simple_tensorflow_serving/commit/02f25974f48e9c07391c158e9c4c715ab943a998 .

**Comment by Gurubux** [comment]
Same error occurred while running a notebook from the Tensorflow site  - [**Build a linear model with Estimators**](https://www.tensorflow.org/tutorials/estimators/linear )
<br>
Download the dataset:
```
from official.wide_deep import census_dataset
from official.wide_deep import census_main

census_dataset.download("/tmp/census_data/")
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-9-fa1d43ace000> in <module>()
>       2 from official.wide_deep import census_main
>       3 
> ----> 4 census_dataset.download("/tmp/census_data/")
> 
> /content/models/official/wide_deep/census_dataset.py in download(data_dir)
>      76 def download(data_dir):
>      77   """Download census data if it is not already present."""
> ---> 78   **tf.gfile.MakeDirs(data_dir)**
>      79 
>      80   training_file_path = os.path.join(data_dir, TRAINING_FILE)
> 
> **AttributeError: module 'tensorflow' has no attribute 'gfile'**

**Comment by tobegit3hub** [comment]
@Gurubux It was resolved in this problem with new TensorFlow APIs.

**Comment by Tarun3679** [comment]
Hi, I am still facing the same issue even after using tensorflow 2.2 and chaning the configuration as mentioned. Please look at image below.
![Screenshot from 2020-05-22 01-09-38](https://user-images.githubusercontent.com/34520609/82598950-15852300-9bc9-11ea-9dca-0b2dd2cae10d.png)

**Comment by NidhiRustagi** [comment]
Same here. Same issue still exists even with Tf2.2.0.  The error comes while working with tokenization.FullTokenizer(vocab_file, do_lower_case) so we cant even go to the file and change it
